version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    env_file:
      - .env.local
    ports:
      - "9000:9000"
    volumes:
      - ./shared:/app/shared:ro
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    depends_on:
      - api
    ports:
      - "8080:80"
    restart: unless-stopped
